jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python311:
        python.version: '3.11'
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'
    maxParallel: 5

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: ./ci.sh tox-4.x docker-6.x
    displayName: 'Tox 4.x, Docker 6.x'

  - script: ./ci.sh tox-4.x docker-5.x
    displayName: 'Tox 4.x, Docker 5.x'

  - script: ./ci.sh tox-4.x docker-4.x
    displayName: 'Tox 4.x, Docker 4.x'
